sudo: false
language: node_js
node_js: 6
before_install:
  - "sh -e /etc/init.d/xvfb start"
env:
  global:
  - ENCRYPTION_LABEL: fefb9ef3c8d6
  - COMMIT_AUTHOR_EMAIL: 'contact@hassanbazzi.com'
before_script:
  - "export DISPLAY=:99.0"
  - until xwininfo -root > /dev/null 2>&1; do echo "waiting for xvfb"; done
cache:
  directories:
    - node_modules
after_success: ./make-bower-build.sh
